routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/hello-world','HelloWorldController@show');
Route::resource('users', 'UserController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HelloWorldController.php
<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Console\ViewClearCommand;
use Illuminate\View\View;

class HelloWorldController extends Controller
{
    public function show()
    {
        return View('hello-world.show');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Model\Classroom;
use Illuminate\Http\Request;
use App\Model\User;
use App\Jobs\SendRegisterEmail;
use StringHelper;

class UserController extends Controller
{
    private $user;
    private $classroom;

    public function __construct(User $user, Classroom $classroom)
    {
        $this->middleware(['auth', 'classable']);
        $this->user = $user;
        $this->classroom = $classroom;
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {
        $this->authorize('staff');

        $data = $request->all();
        $users = $this->user->getUsers($data);
        $classrooms = $this->classroom->getClassrooms();
        return view('users.index', compact(['users', 'classrooms']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('admin');

        $classrooms = $this->classroom->getClassrooms();
        return view('users.create', compact('classrooms'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $data = $request->all();
        $newUser = $this->user->createUser($data);
        if ($newUser) {
            event(new \App\Events\CreatedUser($newUser));
            flash('Thêm mới người dùng thành công')->success();
        }
    }
}

resources/views/hello-world/show.blade.php
<!DOCTYPE html>
<html lang={{ app()->getLocale() }}>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Hello World</title>
</head>
<body>
<h1>Hello world!</h1><br/>
<h2>Hôm nay là ngày: {{date("d-m-Y")}}</h2>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Trang chủ</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Đăng nhập') }}</a></li>
                            <!--<li><a class="nav-link" href="{{ route('register') }}">{{ __('Đăng kí') }}</a></li>-->
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="vi">
@include('layouts.head')
<body>
<div id="wrap">
@include('layouts.header')
<div class="container">
    @yield('content')
</div>
@include('layouts.footer')
</div>
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="text-center" id="footer"><hr>&copy; Copyright {{ date('Y-m-d') }} PHP trainning by LIFETIME technologies</footer>

resources/views/layouts/head.blade.php
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    @yield('title page')
    <link rel="shortcut icon" href="{{ asset('assets/img/454.ico') }}">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{{ asset('css/base.css') }}">
    @yield('stylesheet')
    <script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    @yield('script')
</head>

resources/views/layouts/header.blade.php
<header>
    <div class="col-lg-10 col-lg-offset-1">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Đăng nhập') }}</a></li>
                        <!--<li><a class="nav-link" href="{{ route('register') }}">{{ __('Đăng kí') }}</a></li>-->
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
    <h1 style="margin-left: 100px">@yield('header title')</h1>
    <hr>
    </div>
</header>

resources/views/users/create.blade.php
@extends('layouts.default')
@section('title page')
    <title>Thêm mới người dùng</title>
@endsection
@section('header title')
    Thêm mới Người Dùng
@endsection
@section('content')
    @include('flash::message')
    <div class="col-lg-8 col-lg-offset-1">
        <div class="panel panel-primary ">
            <div class="panel-heading">Thêm Mới Người Dùng
                <div class="pull-right" style="display: inline">
                <a  class="btn btn-primary btn-xs" href="{{ route('users.create') }}">Thêm Mới Người Dùng</a>
                    <a  class="btn btn-primary btn-xs" href="{{ route('users.index') }}">Danh Sách Người Dùng</a>
                </div>
            </div>
            <div class="panel-body">
                <form action="{{route('users.store')}}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group @if($errors->has('classroom_id')) {{'alert alert-danger'}} @endif">
                        <lable for="classroom_id">Lớp</lable>
                        <select
                               required
                               name="classroom_id"
                               class="form-control"
                        >
                            <option></option>
                            @foreach($classrooms as $id => $name)
                            <option value= "{{ $id }}" >{{ $name }}</option>
                            @endforeach
                        </select>
                            {!! $errors->first('classroom_id', '<span class="help-block">:message</span>') !!}
                    </div>
                    <div class="form-group @if($errors->has('mail_address')) {{'alert alert-danger'}} @endif">
                        <lable for="mail_address">Email</lable>
                        <input type="text"
                               placeholder="Enter email"
                               required
                               name="mail_address"
                               spellcheck="false"
                               class="form-control"
                        >
                            {!! $errors->first('mail_address', '<span class="help-block">:message</span>') !!}
                    </div>
                    <div class="form-group @if($errors->has('password')) {{'alert alert-danger'}} @endif">
                        <lable for="password">Mật khẩu</lable>
                        <input type="password"
                               placeholder="Enter password"
                               required
                               name="password"
                               spellcheck="false"
                               class="form-control"
                        >
                            {!! $errors->first('password', '<span class="help-block">:message</span>') !!}
                    </div>
                    <div class="form-group @if($errors->has('password_confirmation')) {{'alert alert-danger'}} @endif">
                        <lable for="password_confirmation">Nhập lại mật khẩu</lable>
                        <input type="password"
                               placeholder="Enter password confirm"
                               required
                               name="password_confirmation"
                               spellcheck="false"
                               class="form-control"
                        >
                            {!! $errors->first('password_confirmation', '<span class="help-block">:message</span>') !!}
                    </div>
                    <div class="form-group @if($errors->has('name')) {{'alert alert-danger'}} @endif">
                        <lable for="name">Tên</lable>
                        <input placeholder="Enter name"
                               name="name"
                               required
                               spellcheck="false"
                               class="form-control"
                        >
                            {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
                    </div>
                    <div class="form-group @if($errors->has('address')) {{'alert alert-danger'}} @endif">
                        <lable for="address">Địa chỉ</lable>
                        <input placeholder="Enter address"
                               name="address"
                               spellcheck="false"
                               class="form-control"
                        >
                            {!! $errors->first('address', '<span class="help-block">:message</span>') !!}
                    </div>
                    <div class="form-group @if($errors->has('phone')) {{'alert alert-danger'}} @endif">
                        <lable for="phone">Số điện thoại</lable>
                        <input placeholder="Enter phone"
                               name="phone"
                               required
                               spellcheck="false"
                               class="form-control"
                        >
                            {!! $errors->first('phone', '<span class="help-block">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <lable for="role">Vai trò</lable>
                        <select id="role" name="role">
                            @foreach(\App\Model\User::$role as $id => $role)
                                <option value="{{ $id }}">{{ $role }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="btn-add" class="btn btn-primary" value="Thêm">
                    </div>
                </form>
            </div>
        </div>
    </div>
    @endsection

resources/views/users/index.blade.php
@extends('layouts.default')
@section('title page')
    <title>Danh sách người dùng</title>
@endsection
@section('header title')
    Danh Sách Người Dùng
@endsection
@section('content')
    <div class="col-lg-10 col-lg-offset-1">
        <div class="panel panel-primary ">
            <div class="panel-heading">Danh Sách Người Dùng
                <div class="pull-right" style="display: inline">
                    <button type="button" class="pull-right btn btn-primary btn-xs" data-toggle="modal" data-target="#search-modal">Tìm kiếm</button>
                    @can('admin')
                        <a class="pull-right btn btn-primary btn-xs"  style="padding-left: 10px" href="{{ route('users.create') }}">Thêm Mới</a>
                    @endcan
                    <a class="pull-right btn btn-primary btn-xs"  style="padding-left: 10px" href="{{ route('users.index') }}">Danh sách</a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-bordered table-striped table-auto table-condensed full_width">
                    <thead class="panel-title">
                    <th class="text-center">Số Thứ Tự</th>
                    <th class="text-center">Lớp</th>
                    <th class="text-center">Địa Chỉ Email</th>
                    <th class="text-center">Tên</th>
                    <th class="text-center">Địa Chỉ</th>
                    <th class="text-center">Số Điện Thoại</th>
                    <th class="text-center">Vai trò</th>
                    <th class="text-center">Sửa</th>
                    <th class="text-center">Xóa</th>
                    </thead>
                    <tbody>

                    @foreach ($users as $index => $user)
                        <tr>
                            <td class="text-center">{{ $index + 1}}</td>
                            <td class="text-center">{{ $user->classroom->name}}</td>
                            <td class="text-center">{{ $user->mail_address }}</td>
                            <td class="text-center">{{ StringHelper::stringToUpper($user->name) }}</td>
                            <td class="text-center">{{ $user->address }}</td>
                            <td class="text-center">{{ $user->phone }}</td>
                            <td class="text-center">{{ \App\Model\User::$role[$user->role] }}</td>
                            <td class="text-center">
                                <a href="{{ route('users.edit',['id' => $user->id]) }}" class="btn btn-xs btn-success">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                </a></td>
                            <td class="text-center">
                                <a href="{{ route('users.destroy',['id' => $user->id]) }}" class="btn btn-xs btn-success">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="text-right">{{ $users->links() }}</div>
            </div>
        </div>
        <!-- Search Modal -->
        <div id="search-modal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header" style="background-color: cornflowerblue">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title" style="color: snow">Tìm kiếm người dùng</h4>
                    </div>
                    <div class="modal-body">
                        <form name="frm-search" method="GET" enctype="multipart/form-data" action="{{route('users.index')}}">
                            <div class="form-group">
                                <label for="classroom_id">Lớp</label>
                                <select multiple class="form-control" name="classroom_id">
                                    @foreach($classrooms as $id => $name)
                                        <option value="{{ $id }}">{{ $name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="mail_address">Email</label>
                                <input type="text" class="form-control" name="mail_address" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" name="name" placeholder="Enter name">
                            </div>
                            <div class="form-group">
                                <label for="address">Address</label>
                                <input type="text" class="form-control" name="address" placeholder="Enter address">
                            </div>
                            <div class="form-group">
                                <label for="address">Phone</label>
                                <input type="text" class="form-control" name="phone" placeholder="Enter phone">
                            </div>
                            <div class="form-group">
                                <input type="submit" class="pull-right btn btn-primary" value="Tìm kiếm">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="pull-right btn btn-primary btn-outline-primary" data-dismiss="modal">Quay lại</button>
                    </div>
                </div>

            </div>
        </div>
        <!-- End search modal -->
    </div>
    @endsection